import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-22T12:00:00+09:00'))
  await page.goto('/')
})

async function search(page: Page) {
  await page.getByRole('button', { name: 'この条件で探す' }).click()
}

test('既定条件で候補を列挙し、空席未照会を明示する', async ({ page }, testInfo) => {
  await expect(page.getByRole('heading', { level: 1 })).toContainText('そのマイルで、')
  await expect(page.getByLabel('出発日の開始')).toHaveValue('2026-10-22')
  await expect(page.getByLabel('出発日の終了')).toHaveValue('2026-11-20')
  await expect(page.locator('.route-card')).toHaveCount(12)
  await expect(page.locator('.availability-note')).toContainText('空席は未照会')
  await expect(page.locator('.result-summary')).toContainText('1名・往復')
  await page.getByRole('button', { name: /さらに12路線を見る/ }).click()
  await expect(page.locator('.route-card')).toHaveCount(24)
  await page.screenshot({ path: testInfo.outputPath('desktop.png'), fullPage: true })
})

test('小さい予算では空状態になり、リセットで候補を復元する', async ({ page }) => {
  await page.getByLabel('使えるマイル').fill('1')
  await search(page)
  await expect(page.getByRole('heading', { name: '条件に合う候補が見つかりませんでした' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'CSV出力' })).toBeDisabled()
  await expect(page.locator('.route-card')).toHaveCount(0)
  await page.getByRole('button', { name: '条件をリセット' }).click()
  await expect(page.getByLabel('使えるマイル')).toHaveValue('60000')
  await expect(page.locator('.route-card')).toHaveCount(12)
})

test('国内線のビジネスを誤って提供しない', async ({ page }) => {
  await page.getByRole('button', { name: '国内線', exact: true }).click()
  await page.getByLabel('座席クラス').selectOption('business')
  await search(page)
  await expect(page.getByRole('heading', { name: '条件に合う候補が見つかりませんでした' })).toBeVisible()
  await expect(page.locator('.route-card')).toHaveCount(0)
})

test('日付逆転をエラーにし、適用済みの結果を保持する', async ({ page }) => {
  await page.getByLabel('出発日の開始').fill('2026-11-21')
  await search(page)
  await expect(page.getByRole('alert')).toContainText('終了日は開始日以降を指定してください。')
  await expect(page.locator('.result-summary')).toContainText('10/22 — 11/20')
  await expect(page.locator('.route-card')).toHaveCount(12)
})

test('シーズンをまたぐ2名往復の合計マイルと復路日を表示する', async ({ page }) => {
  await page.getByRole('button', { name: '国内線', exact: true }).click()
  await page.getByLabel('出発地').selectOption('HND')
  await page.getByLabel('行き先', { exact: true }).selectOption('関西')
  await page.getByLabel('出発日の開始').fill('2026-11-30')
  await page.getByLabel('出発日の終了').fill('2026-11-30')
  await page.getByLabel('人数').selectOption('2')
  await page.getByLabel('旅行日数').selectOption('3')
  await search(page)
  await expect(page.locator('.route-card')).toHaveCount(2)
  await expect(page.locator('.route-price').first()).toContainText('25,000')
  await expect(page.locator('.route-price').first()).toContainText('2名・往復の合計')
  await page.getByRole('button', { name: '日付と詳細' }).first().click()
  const row = page.getByRole('dialog').locator('tbody tr')
  await expect(row).toHaveCount(1)
  await expect(row).toContainText('11/30')
  await expect(row).toContainText('12/3')
  await expect(row).toContainText('レギュラー / ロー')
  await expect(row.locator('td').nth(3)).toHaveText('12,500')
  await expect(row.locator('td').nth(4)).toHaveText('25,000')
})

test('検索条件をURLから復元し、候補を保存・再読込・削除する', async ({ page }) => {
  await page.getByLabel('行き先', { exact: true }).selectOption('韓国')
  await search(page)
  await expect(page).toHaveURL(/search=/)
  await expect(page.locator('.route-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'ソウルを保存', exact: true }).click()
  await page.reload()
  await expect(page.getByLabel('行き先', { exact: true })).toHaveValue('韓国')
  await page.getByRole('button', { name: /保存した候補/ }).click()
  await expect(page.getByRole('heading', { name: /保存した旅の候補/ })).toBeVisible()
  await expect(page.locator('.route-card')).toHaveCount(1)
  await expect(page.locator('.route-card')).toContainText('ソウル')
  await page.getByRole('button', { name: 'ソウルを保存から削除' }).click()
  await expect(page.getByRole('heading', { name: '気になる行き先を、ここに。' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'ソウルを保存', exact: true })).toHaveAttribute('aria-pressed', 'false')
})

test('CSVは未表示分も含む全候補日と人数・マイル・未照会状態を出力する', async ({ page }) => {
  const summary = await page.locator('.result-summary').innerText()
  const count = Number(summary.match(/([\d,]+)件の日付別候補/)![1].replaceAll(',', ''))
  expect(count).toBeGreaterThan(12 * 30)
  const promise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'CSV出力' }).click()
  const download = await promise
  expect(download.suggestedFilename()).toBe('milefinder-2026-09-22.csv')
  const csv = await readFile((await download.path())!, 'utf8')
  expect(csv.startsWith('\uFEFF')).toBe(true)
  const rows = csv.trimEnd().slice(1).split('\r\n')
  expect(rows.length).toBe(count + 1)
  expect(rows[0]).toContain('"合計マイル（全員）","空席確認"')
  for (const row of rows.slice(1)) {
    expect(row).toContain('"往復","エコノミー","1"')
    expect(row).toContain('"未照会（必要マイルの目安）"')
    const cells = row.split(',').map(cell => cell.slice(1, -1))
    expect(Number(cells[15])).toBeLessThanOrEqual(60_000)
    expect(Number(cells[15])).toBe(Number(cells[12]) + Number(cells[13]))
  }
})

test('カレンダーを7日ずつ送り、詳細を開いてリストに戻れる', async ({ page }) => {
  await page.getByRole('button', { name: 'カレンダー表示' }).click()
  await expect(page.locator('.calendar-table')).toBeVisible()
  await expect(page.locator('.calendar-table thead th')).toHaveCount(8)
  await expect(page.getByRole('button', { name: '前の7日' })).toBeDisabled()
  await expect(page.locator('.calendar-top')).toContainText('10/22 — 10/28')
  await page.getByRole('button', { name: '次の7日' }).click()
  await expect(page.locator('.calendar-top')).toContainText('10/29 — 11/4')
  await page.locator('.calendar-cell').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('空席は未照会です。')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'リスト表示' }).click()
  await expect(page.locator('.route-card')).toHaveCount(12)
})

test('スマートフォンで横にはみ出さず、詳細と使い方を閉じられる', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('mobile.png'), fullPage: true })
  await page.getByRole('button', { name: '日付と詳細' }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  const box = await page.getByRole('dialog').boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(390)
  await page.getByRole('button', { name: '閉じる', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '使い方', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('マイルから算出した「候補」は空席確認済みとは限りません。')
  await page.getByRole('button', { name: '閉じる', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'カレンダー表示' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  const overflow = await page.locator('.table-scroll').evaluate(el => el.scrollWidth > el.clientWidth)
  expect(overflow).toBe(true)
})
